# Generated by Django 4.2.22 on 2025-06-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbfc_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-check_in'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='working_hours',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('leave', 'Leave')], default='present', max_length=20),
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='nbfc_attendance',
        ),
    ]
